### ISSUE TITLE
Problems with step 2

### ISSUE THREAD

**Issue by AlessandroPomponio** [carbon-design-system/carbon-tutorial-vue#1435]
Hello,

when trying to follow the second step of the tutorial, I faced some issues that seemed to prevent the pages from working correctly. By looking at @Sw0rdiX's files in PR #1429 I was able to sort out the issues. 

It appears that some of the snippets that use the `.cds` prefix weren't working as expected in my local deployment, and had to be substituted with `.bx`. This happened for example in `LandingPage.vue` and its related `_carbon-overrides.scss`.

Additionally, the build would break when adding styles to [row two](https://carbondesignsystem.com/developing/vue-tutorial/step-2/#row-two). The prefix `carbon--` had to be added to `.landing-page__subheading` and `.landing-page__p` as follows:

```css
.landing-page__subheading {
  @include carbon--type-style('productive-heading-03');
  @include carbon--font-weight('semibold');
}

.landing-page__p {
  @include type-style('productive-heading-03');
  margin-top: $spacing-06;
  margin-bottom: $spacing-08;

  @include carbon--breakpoint-between((320px + 1), md) {
    max-width: 75%;
  }
}
``` 

My branch for step 2 can be found [here](https://github.com/AlessandroPomponio/carbon-tutorial-vue/tree/vue-step-2) in case someone wants to have a look at the dependencies I had installed. 

I will remain available in case more information is required. Thanks in advance.
